### ISSUE TITLE
[JOSS Review] – Community guidelines 

### ISSUE THREAD

**Issue by MaximevdHeijden** [ericfell/rfbzero#35]
Dear authors, 

To improve the community guidelines, could you please make a 'Contribution' section to improve the visibility for third parties? Now it is mentioned before the installation, which is easy to overlook when looking for the contribution guidelines.

This issue is related to openjournals/joss-reviews#6537

**Comment by hjelmj** [comment]
Dear authors, I agree with @MaximevdHeijden, but I also think it could be useful to add it to the repository as a CONTRIBUTING.md file where the contribution instructions are provided.

**Comment by ericfell** [comment]
Thank you both for your suggestions.
We've added a contribution section to the documents FAQ and a CONTRIBUTING.md in the root repo,
via #40 (now merged).
related to openjournals/joss-reviews#6537
