### ISSUE TITLE
[JOSS Review] - Suggestions for the documentation

### ISSUE THREAD

**Issue by MaximevdHeijden** [ericfell/rfbzero#37]
Dear authors,

Some very minor suggestions for the documentation:

- Could you add the installation section to the documentation? Copy-paste from your README file is more than fine, but then everything can be found in the same documentation. 

- The crossover documentation mentions that the class is still limited to symmetric cells and that current-driven crossover cannot be simulated. If you are not working on this yourself anymore by any chance, it would be nice to make a list of possible extensions of the code for others to contribute to.  

This issue is related to https://github.com/openjournals/joss-reviews/issues/6537

**Comment by ericfell** [comment]
Thank you for the suggestions. 

Regarding the first bullet point, we've added the installation section to the documentation [examples notebook](https://github.com/ericfell/rfbzero/blob/main/docs/source/examples/simulate_RFB_example.ipynb) in #40, and the same information can be found on the homepage [readthedocs for rfbzero](https://rfbzero.readthedocs.io/en/latest/index.html).

Regarding the second point, we've opened issue #41 as a feature request to include current-driven crossover. Guiding information for this feature is provided there.

related to openjournals/joss-reviews#6537
